user nginx;
worker_processes auto;
daemon off;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    server_tokens off;

    sendfile on;
    keepalive_timeout 65;
    gzip on;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    map $http_x_forwarded_proto $forwarded_proto {
        default $http_x_forwarded_proto;
        '' $scheme;
    }

    map $http_x_forwarded_port $forwarded_port {
        default $http_x_forwarded_port;
        '' $server_port;
    }

    map $forwarded_proto $forwarded_ssl {
        https on;
        default off;
    }

    include /etc/nginx/conf.d/*.conf;
}
